version: '3'
services:

  backend:
    container_name: thesis-backend
    restart: unless-stopped
    image: thesis-backend
    build: ./backend/
    ports:
      - "5050:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./results:/backend/results

  app:
    container_name: thesis-frontend
    restart: unless-stopped
    image: thesis-frontend
    build: ./frontend/
    ports:
      - "3030:3000"
    tty: true
